name: photopin
description: "A new Flutter project."
publish_to: 'none'
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  google_fonts: ^6.3.3
  intl: ^0.20.2
  path: ^1.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/svg/

